baseurl = "https://chrismaughan.com"
title = "ChrisMaughan.com"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "www-chrismaughan-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-142140471-1"
enableRobotsTXT = true
[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  title = "ChrisMaughan.com"
  description = "ChrisMaughan.com"
  copyright = "&copy;2019 Chris Maughan"
  sidebarAbout = [
    "I'm a programmer, working for NVIDIA.",
    "This site contains screenshots of personal & professional projects.",
    "Based in York, UK"
    ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Projects"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Presentations"
  url = "presentations/"

  [[params.navlinks]]
  name = "Photos"
  url = "photos/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  twitter       = "https://twitter.com/cmaughan"
  linkedin      = "https://linkedin.com/in/chrismaughan"
  stackoverflow = "https://stackoverflow.com/users/18942/cmaughan"
  github        = "https://github.com/cmaughan"
